### ISSUE TITLE
問題 ID を変更した際に、元の問題 ID の問題文ファイルが消えてほしい

### ISSUE THREAD

**Issue by riantkb** [tsutaj/statements-manager#137]
`problem.toml` で `id = "X"` として `ss-out/X.html` を生成したのち、`id = "Y"` と変更して問題文を再生成すると `ss-out/X.html` はそのまま残るが、紛らわしいので消すことに不利益がなければ消えるとありがたい。

**Comment by tsutaj** [comment]
たしかに・・・

ある拡張子 `ext` で `ss-manager run -o ext WORKING_DIR` したときに、`WORKING_DIR/ss-out/*.ext` をすべて削除してから生成物を作るように今後変更します。

**Comment by tsutaj** [comment]
> WORKING_DIR/ss-out/*.ext をすべて削除してから生成物を作るように

実行結果をキャッシュして、必要に応じて再生成する機構があるので、単純に全部削除するのはよくないと思われる。

現状の挙動を整理すると、以下の通り。

|前の実行|今の実行|どうなる|
|---|---|---|
|ファイルが存在しない|ファイルを作る|新規作成（キャッシュに項目が追加される）|
|ファイルが存在する|ファイルを作る|新しくなっていたら置き換える（キャッシュの項目を更新）|
|ファイルが存在する|（リネームなどの理由で）ファイルを作らない|何もしない（キャッシュも残ったまま）|

最後の行の挙動がよくなさそう。  
とはいえ、 id が同じなら残しておいたほうが良い気はする。 `A.html` を生成したときに `A.pdf` が消えたりしたら困りそう。  
違う id から生成されたであろうファイル名（およびキャッシュ項目）だったら削除する、とするのがよさそう。
