### ISSUE TITLE
問題ディレクトリを指定して実行した際にテンプレートの設定が反映されない

### ISSUE THREAD

**Issue by riantkb** [tsutaj/statements-manager#149]
`problemset.toml` で template を指定しているとき、template 設定が反映されるかどうかが以下の 3 つの例で異なるのが解消されて欲しい気持ちがあります。

```sh
ss-manager run # 反映される
ss-manager run A/ # 反映されない
cd A/; ss-manager run # 反映されない
```

----

解決案としては以下を考えていましたが、一長一短あるなぁと思っています。

- 一階層上の `problemset.toml` を見に行く
  - これが問題なくできるなら苦労しないが…
- `problem.toml` で template を指定できる
  - `sample_template_path = "../templates/sample_default.html"` みたいな
  - 全体実行の際に `problemset.toml` と両方で定義されていたらより子である `problem.toml` の設定を優先するのが自然そう
  - そもそもテンプレートの設定は（problemset に対するテンプレート設定を除き） `problem.toml` （だけ）にあるべき？
    - 「インタラクティブ問題のときは別のテンプレートを使いたい」みたいなケースで問題ごとにテンプレートを変える用途がギリギリ存在するかも
    - でも同じ設定を 10 回とか書くのはめんどい……

**Comment by tsutaj** [comment]
親方向にディレクトリを辿っていって、はじめに見つかった problemset.toml を見に行く案は考えていました。（面倒なので先送りになっていますが・・・）

確か rime では問題ディレクトリの階層にいても親方向にある PROJECT 等が有効になった記憶があるので、実装を参考にしつつ方向性を決めてみます。

**Comment by tsutaj** [comment]
> 確か rime では問題ディレクトリの階層にいても親方向にある PROJECT 等が有効になった記憶がある

コードを確かめたら、やはりこのような機構があった。同じように対処したい。

https://github.com/icpc-jag/rime/blob/5f5d83251b51d335af02b437ddf0b96161cf5254/rime/core/main.py#L55
